version: "3"

services:
  postgresautomessage:
    image: postgres:10.2
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: 'nyxtc'
      POSTGRES_DB: 'automessage'
    ports:
      - "5432:5432"
    labels:
      - 'traefik.docker.network=laravel'
      - 'traefik.enable=true'
      - 'traefik.backend=postgresautomessage'
      - 'traefik.port=3306'
      - 'traefik.frontend.rule=Host:postgresautomessage.docker.local'

  php:
    image: wodby/php:7.2-4.2.2
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_BLACKFIRE: 1
    volumes:
      - ./:/var/www/html

  nginxautomessage:
    image: wodby/php-nginx:1.13-4.0.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/public
    user: 1000:101
    volumes:
      - ./:/var/www/html
      - ./certs:/certs/
      - ./docker/templates:/etc/nginx/conf.d
    labels:
      - 'traefik.docker.network=laravel'
      - 'traefik.enable=true'
      - 'traefik.backend=nginxautomessage'
      - 'traefik.port=80'
      - 'traefik.logs.frontend.rule=Host:automessage.docker.local;PathPrefix:/log-viewer'
      - 'traefik.logs.frontend.auth.basic.users=nyxtc:$$apr1$$n4tqay70$$Y6K.H9JYEhofKykkTMTQ61'
      - 'traefik.app.frontend.rule=Host:automessage.docker.local'

  portainer:
    image: portainer/portainer
    container_name: "portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.enable=true'
      - "traefik.docker.network=laravel"
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:automessageportainer.docker.local'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '3306:3306'
      - '9000:9000'
      - '80:80'
      - '8000:80'
      - '8081:8081' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=laravel"
      - "traefik.port=8081"

  dem:
    image: quaide/dem:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf.yml:/app/conf.yml
    labels:
      - "traefik.docker.network=laravel"

networks:
  automessage:
    driver: bridge
    ipam:
      config:
        -
          subnet: 172.55.0.0/16